- Document-Processing/PDF/PDF-Library/NET/Assemblies-Required.md
Hi All,
Task Id: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/971729/
Task Name: Sidebar contents are not aligned properly in UG documentation
Regards,
Sameerkhan N
> 971729: Resolved sidebar contents aligned properly in UG documentation.

- Document-Processing/PDF/PDF-Library/NET/Working-with-forms.md
Hi All,
Task Id: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/963561/
Task Name: Changing checkmark and radio button colors in PDF
Regards,
Sameerkhan N
> 963561-ug: Added UG documentation for changing the foreground color of radio buttons and checkbox checkers.

- Document-Processing/PDF/PDF-Library/NET/Working-with-OCR/AWS-Textract.md
Hi All,
Resolved the CI failures.
Regards,
Sameerkhan N
> 963596-2: Resolved CI failures

- Document-Processing/PDF/PDF-Library/NET/Working-with-Headers-and-Footers.md
- Document-Processing/PDF/PDF-Library/NET/Working-with-forms.md
Hi All,
Task Id: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/963596/
Task name: How to draw dynamic footers to the sections of the PDF document
Regards,
Sameerkhan N
> 963596-ug: Added dynamic footers to the sections of the PDF document.

- Document-Processing/PDF/PDF-Library/NET/Working-with-Text.md
Hi All,
Task Id:https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/935627
Task Name:Need to add this FAQ details about standard fonts in working with Text
Regards,
Sameerkhan N
> 935627-ug: Added FAQ for standard fonts in working with text.

- Document-Processing/PDF/PDF-Library/NET/Working-with-OCR/Linux.md
Hi All,
Task Id: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/974954
Task Name:Update the OCR linux prerequisites
Regards,
Sameerkhan N
> 974954-ug: Updated the OCR linux prerequisites

- Document-Processing/PDF/PDF-Library/NET/Working-with-OCR/AWS-Textract.md
- Document-Processing/PDF/PDF-Library/NET/Working-with-OCR/Azure-Kubernetes-Service.md
- Document-Processing/PDF/PDF-Library/NET/Working-with-OCR/Azure-Vision.md
- Document-Processing/PDF/PDF-Library/NET/Working-with-OCR/Docker.md
- Document-Processing/PDF/PDF-Library/NET/Working-with-OCR/Dot-NET-Core.md
- Document-Processing/PDF/PDF-Library/NET/Working-with-OCR/Dot-NET-Framework.md
- Document-Processing/PDF/PDF-Library/NET/Working-with-OCR/Linux.md
- Document-Processing/PDF/PDF-Library/NET/Working-with-OCR/Working-with-OCR.md
- Document-Processing/PDF/PDF-Library/NET/Working-with-OCR/azure.md
- Document-Processing/PDF/PDF-Library/NET/Working-with-OCR/blazor.md
- Document-Processing/PDF/PDF-Library/NET/Working-with-OCR/net-core.md
Hi All,
Task Id:https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/975357/
Task Name:Update proper NuGet package details in package requirement
Regards,
Sameerkhan N
> 975357-ug: OCR NuGet package changes updated.

- Document-Processing/Excel/Spreadsheet/React/cell-range.md
- Document-Processing/Excel/Spreadsheet/React/clipboard.md
- Document-Processing/Excel/Spreadsheet/React/context-menu.md
- Document-Processing/Excel/Spreadsheet/React/data-binding.md
- Document-Processing/Excel/Spreadsheet/React/editing.md
- Document-Processing/Excel/Spreadsheet/React/filter.md
- Document-Processing/Excel/Spreadsheet/React/formatting.md
- Document-Processing/Excel/Spreadsheet/React/formulas.md
- Document-Processing/Excel/Spreadsheet/React/freeze-pane.md
- Document-Processing/Excel/Spreadsheet/React/getting-started.md
- Document-Processing/Excel/Spreadsheet/React/global-local.md
- Document-Processing/Excel/Spreadsheet/React/how-to/change-active-sheet.md
- Document-Processing/Excel/Spreadsheet/React/how-to/create-a-object-structure.md
- Document-Processing/Excel/Spreadsheet/React/how-to/identify-the-context-menu-opened.md
- Document-Processing/Excel/Spreadsheet/React/illustrations.md
- Document-Processing/Excel/Spreadsheet/React/link.md
- Document-Processing/Excel/Spreadsheet/React/notes.md
- Document-Processing/Excel/Spreadsheet/React/open-save.md
- Document-Processing/Excel/Spreadsheet/React/print.md
- Document-Processing/Excel/Spreadsheet/React/protect-sheet.md
- Document-Processing/Excel/Spreadsheet/React/ribbon.md
- Document-Processing/Excel/Spreadsheet/React/rows-and-columns.md
- Document-Processing/Excel/Spreadsheet/React/scrolling.md
- Document-Processing/Excel/Spreadsheet/React/searching.md
- Document-Processing/Excel/Spreadsheet/React/selection.md
- Document-Processing/Excel/Spreadsheet/React/sort.md
- Document-Processing/Excel/Spreadsheet/React/template.md
- Document-Processing/Excel/Spreadsheet/React/undo-redo.md
- Document-Processing/Excel/Spreadsheet/React/worksheet.md
Adding Document Processing React File Path into Spreadsheet UG React File.
Task ID: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/976311
> 976311: Adding Document Processing React File Path into Spreadsheet UG React File

- Document-Processing-toc.html
977561: Modified Javascript, Typescript Documentation Revamp
> 977561: Modified UG documentation JS and TS toc file

- Document-Processing/PDF/Conversions/HTML-To-PDF/NET/features.md
Hi All,
Task Id: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/978142
Task name: Need to add content related to new feature in HTML to PDF conversion under the Features section
Regards,
Sameerkhan N
> 978142-ug: Added content related to new feature in HTML to PDF conversion under the Features section

- Document-Processing/PDF/PDF-Library/NET/Working-with-Annotations.md
- Document-Processing/PDF/PDF-Library/NET/Working-with-forms.md
Hi All,
Task Id: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/978144
Task Name: Retrieving Custom Values from PDF Annotations and form fields.
Regards,
Sameerkhan N
> 978144-ug: Retrieving Custom Values from PDF Annotations and form fields.

- Document-Processing/Word/Word-Processor/angular/document-editor/getting-started.md
- Document-Processing/Word/Word-Processor/asp-net-core/how-to/auto-save-document.md
- Document-Processing/Word/Word-Processor/asp-net-core/how-to/hide-tool-bar-and-properties-pane.md
- Document-Processing/Word/Word-Processor/asp-net-core/link.md
- Document-Processing/Word/Word-Processor/asp-net-core/track-changes.md
- Document-Processing/Word/Word-Processor/asp-net-mvc/document-editor/comments.md
- Document-Processing/Word/Word-Processor/blazor/document-editor/how-to/retrieve-the-bookmark-content-as-text.md
- Document-Processing/Word/Word-Processor/javascript-es5/document-editor/bookmark.md
- Document-Processing/Word/Word-Processor/javascript-es5/document-editor/content-control.md
- Document-Processing/Word/Word-Processor/javascript-es5/document-editor/dialog.md
- Document-Processing/Word/Word-Processor/javascript-es5/document-editor/how-to/resize-document-editor.md
- Document-Processing/Word/Word-Processor/javascript-es5/document-editor/print.md
- Document-Processing/Word/Word-Processor/javascript-es6/document-editor/server-deployment/how-to-publish-documenteditor-web-api-application-in-azure-app-service-from-visual-studio.md
> 977561: Solved error

- Document-Processing-toc.html
- Document-Processing/PDF/Smart-PDF-Viewer/blazor/groq-service.md
Added UG for Groq Custom AI service in Smart PDF Viewer
> 977889: Added UG for Groq Custom AI service in Smart PDF Viewer

- Document-Processing-toc.html
Task - [974087](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/974087)-->Update the Spreadsheet UG sections from WPF and WF to document process section
Link - [Link ](https://teams.microsoft.com/l/message/19:50b9bf56d9754432a3788c327efb62ba@thread.skype/1754309499410?tenantId=77f1fe12-b049-4919-8c50-9fb41e5bb63b&groupId=dd8d2747-3c75-49c9-8b32-02962f1b5fdf&parentMessageId=1754309499410&teamName=Desktop%20Team&channelName=Confirmation%20Follow-ups&createdTime=1754309499410)
* Remove the  ReplaceUsingAutomation Link in toc.html
* Add the current location link
> ES-974087-Update the Spreadsheet UG sections from the UWP,WPF and WF in document processing toc.html

- Document-Processing-toc.html
- Document-Processing/PDF/Smart-PDF-Viewer/blazor/custom-ai-service.md
- Document-Processing/PDF/Smart-PDF-Viewer/blazor/deepseek-service.md
- Document-Processing/PDF/Smart-PDF-Viewer/blazor/document-summarizer.md
- Document-Processing/PDF/Smart-PDF-Viewer/blazor/how-to/User-Token-with-Custom-AI-service.md
979000: Smart PDF Viewer UG document Preparation and Testing
> 979000: Smart PDF Viewer UG document Preparation and Testing

- Document-Processing/Word/Word-Processor/react/global-local.md
- Document-Processing/Word/Word-Processor/react/how-to/disable-drag-and-drop.md
- Document-Processing/Word/Word-Processor/react/overview.md
- Document-Processing/Word/Word-Processor/react/server-deployment/how-to-deploy-word-processor-server-docker-container-in-azure-app-service.md
- Document-Processing/Word/Word-Processor/react/server-deployment/how-to-deploy-word-processor-server-docker-container-in-azure-kubernetes-service.md
- Document-Processing/Word/Word-Processor/react/server-deployment/how-to-publish-documenteditor-web-api-application-in-azure-app-service-from-visual-studio.md
- Document-Processing/Word/Word-Processor/react/server-deployment/word-processor-server-docker-image-overview.md
Resolved the UG documentation issue for react platform
> 979545: Resolved the UG documentation issue for react platform

- Document-Processing/Word/Word-Processor/vue/server-deployment/how-to-deploy-documenteditor-java-web-api-in-azure.md
- Document-Processing/Word/Word-Processor/vue/server-deployment/how-to-deploy-word-processor-server-docker-container-in-azure-app-service.md
- Document-Processing/Word/Word-Processor/vue/server-deployment/how-to-deploy-word-processor-server-docker-container-in-azure-kubernetes-service.md
- Document-Processing/Word/Word-Processor/vue/server-deployment/how-to-publish-documenteditor-web-api-application-in-azure-app-service-from-visual-studio.md
977566: Getting started page link has been changed from javascript to vue
> 977566: Modified redirection link for getting started

- Document-Processing/Word/Word-Processor/javascript-es5/server-deployment/word-processor-server-docker-image-overview.md
977561: Modified code for JS-es5
> 977561: Modified code for JS-es5

- Document-Processing/Word/Word-Processor/angular/global-local.md
- Document-Processing/Word/Word-Processor/angular/history.md
- Document-Processing/Word/Word-Processor/angular/how-to/disable-drag-and-drop.md
- Document-Processing/Word/Word-Processor/angular/how-to/hide-tool-bar-and-properties-pane.md
Resolved the error issue in Angular
> 977559: Resolved the error issue in Angular

- Document-Processing/Excel/Spreadsheet/Vue/cell-range.md
- Document-Processing/Excel/Spreadsheet/Vue/clipboard.md
- Document-Processing/Excel/Spreadsheet/Vue/context-menu.md
- Document-Processing/Excel/Spreadsheet/Vue/data-binding.md
- Document-Processing/Excel/Spreadsheet/Vue/docker-deployment.md
- Document-Processing/Excel/Spreadsheet/Vue/editing.md
- Document-Processing/Excel/Spreadsheet/Vue/feature-list.md
- Document-Processing/Excel/Spreadsheet/Vue/filter.md
- Document-Processing/Excel/Spreadsheet/Vue/formatting.md
- Document-Processing/Excel/Spreadsheet/Vue/formulas.md
- Document-Processing/Excel/Spreadsheet/Vue/freeze-pane.md
- Document-Processing/Excel/Spreadsheet/Vue/getting-started.md
- Document-Processing/Excel/Spreadsheet/Vue/global-local.md
- Document-Processing/Excel/Spreadsheet/Vue/illustrations.md
- Document-Processing/Excel/Spreadsheet/Vue/keyboard-shortcuts.md
- Document-Processing/Excel/Spreadsheet/Vue/link.md
- Document-Processing/Excel/Spreadsheet/Vue/open-save.md
- Document-Processing/Excel/Spreadsheet/Vue/performance-best-practices.md
- Document-Processing/Excel/Spreadsheet/Vue/protect-sheet.md
- Document-Processing/Excel/Spreadsheet/Vue/ribbon.md
- Document-Processing/Excel/Spreadsheet/Vue/rows-and-columns.md
- Document-Processing/Excel/Spreadsheet/Vue/scrolling.md
- Document-Processing/Excel/Spreadsheet/Vue/searching.md
- Document-Processing/Excel/Spreadsheet/Vue/selection.md
- Document-Processing/Excel/Spreadsheet/Vue/sort.md
- Document-Processing/Excel/Spreadsheet/Vue/template.md
- Document-Processing/Excel/Spreadsheet/Vue/undo-redo.md
- Document-Processing/Excel/Spreadsheet/Vue/vue-3-getting-started.md
- Document-Processing/Excel/Spreadsheet/Vue/worksheet.md
Updated all URL'S for Vue platform.
Task Link - https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/977208/
> 977208: Updated URL'S for Vue platform

- Document-Processing/Excel/Spreadsheet/Javascript-ES5/docker-deployment.md
- Document-Processing/Excel/Spreadsheet/Javascript-ES5/feature-list.md
- Document-Processing/Excel/Spreadsheet/Javascript-ES5/formulas.md
- Document-Processing/Excel/Spreadsheet/Javascript-ES5/getting-started.md
- Document-Processing/Excel/Spreadsheet/Javascript-ES5/open-save.md
- Document-Processing/Excel/Spreadsheet/Javascript-ES5/performance-best-practices.md
Updated all URL'S for Javascript platform.
Task: (https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/977397/)
> 977397: Updated URL for Javascript Platform

- Document-Processing/Excel/Spreadsheet/Angular/cell-range.md
- Document-Processing/Excel/Spreadsheet/Angular/clipboard.md
- Document-Processing/Excel/Spreadsheet/Angular/context-menu.md
- Document-Processing/Excel/Spreadsheet/Angular/data-binding.md
- Document-Processing/Excel/Spreadsheet/Angular/docker-deployment.md
- Document-Processing/Excel/Spreadsheet/Angular/editing.md
- Document-Processing/Excel/Spreadsheet/Angular/filter.md
- Document-Processing/Excel/Spreadsheet/Angular/formatting.md
- Document-Processing/Excel/Spreadsheet/Angular/formulas.md
- Document-Processing/Excel/Spreadsheet/Angular/freeze-pane.md
- Document-Processing/Excel/Spreadsheet/Angular/getting-started.md
- Document-Processing/Excel/Spreadsheet/Angular/global-local.md
- Document-Processing/Excel/Spreadsheet/Angular/illustrations.md
- Document-Processing/Excel/Spreadsheet/Angular/keyboard-shortcuts.md
- Document-Processing/Excel/Spreadsheet/Angular/link.md
- Document-Processing/Excel/Spreadsheet/Angular/mobile-responsiveness.md
- Document-Processing/Excel/Spreadsheet/Angular/open-save.md
- Document-Processing/Excel/Spreadsheet/Angular/performance-best-practices.md
- Document-Processing/Excel/Spreadsheet/Angular/protect-sheet.md
- Document-Processing/Excel/Spreadsheet/Angular/ribbon.md
- Document-Processing/Excel/Spreadsheet/Angular/rows-and-columns.md
- Document-Processing/Excel/Spreadsheet/Angular/scrolling.md
- Document-Processing/Excel/Spreadsheet/Angular/searching.md
- Document-Processing/Excel/Spreadsheet/Angular/selection.md
- Document-Processing/Excel/Spreadsheet/Angular/sort.md
- Document-Processing/Excel/Spreadsheet/Angular/template.md
- Document-Processing/Excel/Spreadsheet/Angular/undo-redo.md
- Document-Processing/Excel/Spreadsheet/Angular/worksheet.md
Changed URLs for Angular Platform
Task ID: 977395(https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/977395/)
> 977395: Changed URLs for Angular Platform

- Document-Processing/Excel/Spreadsheet/React/cell-range.md
- Document-Processing/Excel/Spreadsheet/React/clipboard.md
- Document-Processing/Excel/Spreadsheet/React/context-menu.md
- Document-Processing/Excel/Spreadsheet/React/editing.md
- Document-Processing/Excel/Spreadsheet/React/filter.md
- Document-Processing/Excel/Spreadsheet/React/formatting.md
- Document-Processing/Excel/Spreadsheet/React/formulas.md
- Document-Processing/Excel/Spreadsheet/React/freeze-pane.md
- Document-Processing/Excel/Spreadsheet/React/global-local.md
- Document-Processing/Excel/Spreadsheet/React/illustrations.md
- Document-Processing/Excel/Spreadsheet/React/keyboard-shortcuts.md
- Document-Processing/Excel/Spreadsheet/React/link.md
- Document-Processing/Excel/Spreadsheet/React/open-save.md
- Document-Processing/Excel/Spreadsheet/React/protect-sheet.md
- Document-Processing/Excel/Spreadsheet/React/ribbon.md
- Document-Processing/Excel/Spreadsheet/React/rows-and-columns.md
- Document-Processing/Excel/Spreadsheet/React/scrolling.md
- Document-Processing/Excel/Spreadsheet/React/searching.md
- Document-Processing/Excel/Spreadsheet/React/selection.md
- Document-Processing/Excel/Spreadsheet/React/sort.md
- Document-Processing/Excel/Spreadsheet/React/template.md
- Document-Processing/Excel/Spreadsheet/React/undo-redo.md
- Document-Processing/Excel/Spreadsheet/React/worksheet.md
Changed URLs for React Platform
Task ID: 977395(https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/977395/)
> 977395: Changed spreadsheet example URLs

- Document-Processing/Excel/Spreadsheet/ASP-NET-CORE/docker-deployment.md
- Document-Processing/Excel/Spreadsheet/ASP-NET-CORE/feature-list.md
- Document-Processing/Excel/Spreadsheet/ASP-NET-CORE/formulas.md
- Document-Processing/Excel/Spreadsheet/ASP-NET-CORE/getting-started-core.md
- Document-Processing/Excel/Spreadsheet/ASP-NET-CORE/performance-best-practices.md
- Document-Processing/Excel/Spreadsheet/ASP-NET-CORE/sort.md
- Document-Processing/Excel/Spreadsheet/ASP-NET-MVC/docker-deployment.md
- Document-Processing/Excel/Spreadsheet/ASP-NET-MVC/feature-list.md
- Document-Processing/Excel/Spreadsheet/ASP-NET-MVC/formulas.md
- Document-Processing/Excel/Spreadsheet/ASP-NET-MVC/getting-started-mvc.md
- Document-Processing/Excel/Spreadsheet/ASP-NET-MVC/performance-best-practices.md
- Document-Processing/Excel/Spreadsheet/ASP-NET-MVC/sort.md
Resolved broken links for spreadsheet for asp-net-core and asp-core-mvc
Task: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/976311
> 976311: Resolved broken links for spreadsheet

- Document-Processing/Word/Word-Processor/react/accessibility.md
- Document-Processing/Word/Word-Processor/react/chart.md
- Document-Processing/Word/Word-Processor/react/dialog.md
- Document-Processing/Word/Word-Processor/react/document-management.md
- Document-Processing/Word/Word-Processor/react/export.md
- Document-Processing/Word/Word-Processor/react/getting-started.md
- Document-Processing/Word/Word-Processor/react/how-to/customize-context-menu.md
- Document-Processing/Word/Word-Processor/react/how-to/enable-ruler-in-document-editor-component.md
- Document-Processing/Word/Word-Processor/react/how-to/open-default-document.md
- Document-Processing/Word/Word-Processor/react/how-to/read-by-default.md
- Document-Processing/Word/Word-Processor/react/how-to/show-hide-spinner.md
- Document-Processing/Word/Word-Processor/react/import.md
- Document-Processing/Word/Word-Processor/react/link.md
- Document-Processing/Word/Word-Processor/react/list-format.md
- Document-Processing/Word/Word-Processor/react/print.md
- Document-Processing/Word/Word-Processor/react/restrict-editing.md
- Document-Processing/Word/Word-Processor/react/right-to-left.md
- Document-Processing/Word/Word-Processor/react/scrolling-zooming.md
- Document-Processing/Word/Word-Processor/react/view.md
980276: Modified the preview sample link
> 980276: Modified the preview sample link

- Document-Processing/Word/Word-Processor/asp-net-core/how-to/override-the-keyboard-shortcuts.md
- Document-Processing/Word/Word-Processor/javascript-es5/how-to/override-the-keyboard-shortcuts.md
- Document-Processing/Word/Word-Processor/javascript-es5/table-of-contents.md
- Document-Processing/Word/Word-Processor/javascript-es6/dialog.md
- Document-Processing/code-snippet/document-editor/javascript-es6/document-editor/dialog-cs8/index.js
- Document-Processing/code-snippet/document-editor/javascript-es6/document-editor/dialog-cs8/index.ts
> 980280: Resolved Issues in UG

- Document-Processing/Word/Word-Processor/angular/accessibility.md
- Document-Processing/Word/Word-Processor/angular/bookmark.md
- Document-Processing/Word/Word-Processor/angular/chart.md
- Document-Processing/Word/Word-Processor/angular/dialog.md
- Document-Processing/Word/Word-Processor/angular/document-management.md
- Document-Processing/Word/Word-Processor/angular/export.md
- Document-Processing/Word/Word-Processor/angular/find-and-replace.md
- Document-Processing/Word/Word-Processor/angular/getting-started.md
- Document-Processing/Word/Word-Processor/angular/how-to/customize-context-menu.md
- Document-Processing/Word/Word-Processor/angular/how-to/default-read-only.md
- Document-Processing/Word/Word-Processor/angular/how-to/enable-ruler-in-document-editor-component.md
- Document-Processing/Word/Word-Processor/angular/how-to/open-default-document.md
- Document-Processing/Word/Word-Processor/angular/how-to/override-the-keyboard-shortcuts.md
- Document-Processing/Word/Word-Processor/angular/how-to/show-hide-spinner.md
- Document-Processing/Word/Word-Processor/angular/image.md
- Document-Processing/Word/Word-Processor/angular/import.md
- Document-Processing/Word/Word-Processor/angular/link.md
- Document-Processing/Word/Word-Processor/angular/list-format.md
- Document-Processing/Word/Word-Processor/angular/paragraph-format.md
- Document-Processing/Word/Word-Processor/angular/print.md
- Document-Processing/Word/Word-Processor/angular/right-to-left.md
- Document-Processing/Word/Word-Processor/angular/scrolling-zooming.md
- Document-Processing/Word/Word-Processor/angular/table-of-contents.md
- Document-Processing/Word/Word-Processor/angular/table.md
- Document-Processing/Word/Word-Processor/angular/view.md
Resolved preview changes issue in Angular platform.
> 977559: Resolved preview changes issue in Angular platform.

- Document-Processing/Word/Word-Processor/javascript-es5/how-to/override-the-keyboard-shortcuts.md
980280: Resolved issue in JS-ES5 platform
> 980280: Resolved issue in JS-ES5 platform

- Document-Processing/Excel/Spreadsheet/UWP/Formatting.md
- Document-Processing/Excel/Spreadsheet/UWP/Working-with-SfSpreadsheet.md
- Document-Processing/Excel/Spreadsheet/WPF/Formatting.md
- Document-Processing/Excel/Spreadsheet/WPF/Localization.md
- Document-Processing/Excel/Spreadsheet/WPF/Working-with-SfSpreadsheet.md
- Document-Processing/Excel/Spreadsheet/Winforms/Formatting.md
- Document-Processing/Excel/Spreadsheet/Winforms/Sorting-and-Filtering.md
- Document-Processing/Excel/Spreadsheet/Winforms/Working-with-Spreadsheet.md
Link - [Link ](https://teams.microsoft.com/l/message/19:50b9bf56d9754432a3788c327efb62ba@thread.skype/1754309499410?tenantId=77f1fe12-b049-4919-8c50-9fb41e5bb63b&groupId=dd8d2747-3c75-49c9-8b32-02962f1b5fdf&parentMessageId=1754309499410&teamName=Desktop%20Team&channelName=Confirmation%20Follow-ups&createdTime=1754309499410)
* update the old URL in UWP,WF and WPF to document-processing
> ES-Hotfix-Replaced Spreadsheet link with updated document-processing based documentation URL 

- Document-Processing/PDF/PDF-Library/NET/Working-with-forms.md
Hi All,
Task Id: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/979044/
Task Name: Need to add the DisableAutoFormat API in the documentation
Regards,
Sameerkhan N
> 979044-ug: Added the DisableAutoFormat API in the documentation

- Document-Processing/PDF/PDF-Library/NET/Working-with-Text.md
Hi All,
Task Id: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/978489/
Task name: Need to update the FAQ (Working with Text)
Regards,
Sameerkhan N
> 978489-ug: Added FAQ content in working with text.

- Document-Processing/PDF/PDF-Library/NET/Working-with-PDF-Conformance.md
Hi All,
Task Id: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/980642
Task Name: Integrate Video Link into PDF Conformance Section of User Guide Documentation
Regards,
Sameerkhan N
> 980642-ug: Added YouTube video link in PDF conformance

- Document-Processing/PDF/PDF-Library/NET/Working-with-Named-Destination.md
Hi 
|Title|Description|
|--|--|
|Task Category|Site Audir- SERPSTAT Issue fixes| Https page links to http
|Content Task Link/Mail Screenshot| NA|
|UX task| NA|
|Hotfix|https://github.com/syncfusion-content/document-processing-docs/pull/1390
|Ticket/Task link|https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/207648
|Excel/SharePoint link|
|Changes made|Reason for changes|
|--|--|
|HTTPS-page-links-toHTTP| To avoid redirection error|.
Regards,
Mercy A.
> 207648-Site-Audit-SERPTAT-Help-Domain-Https-page-links-to-Http-

- Document-Processing/PDF/PDF-Library/NET/Working-with-Security.md
Hi All,
Task Id: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/261104
Task name: Need to create UG documentation for Decrypting Encrypted PDF files.
Regards,
Sameerkhan N
> 261104-ug: Created UG documentation for Decrypting Encrypted PDF files.

- Document-Processing/PDF/PDF-Viewer/blazor/how-to/prevent-scrolling.md
- Document-Processing/PDF/PDF-Viewer/blazor/how-to/print-large-page-document.md
- Document-Processing/PDF/PDF-Viewer/blazor/how-to/processing-large-files-without-increasing-maximum-message-size.md
- Document-Processing/PDF/PDF-Viewer/blazor/how-to/reduce-slowness-while-running-the-wasm-sample-in-Visual-Studio.md
- Document-Processing/PDF/PDF-Viewer/blazor/how-to/refer-SfPdfViewer-script-in-application.md
- Document-Processing/PDF/PDF-Viewer/blazor/how-to/render-ej2-pdf-viewer-in-blazor.md
- Document-Processing/PDF/PDF-Viewer/blazor/how-to/render-n-pages-scrolling.md
- Document-Processing/PDF/PDF-Viewer/blazor/how-to/stretch-the-sfpdfviewer-size-to-its-container.md
- Document-Processing/PDF/PDF-Viewer/blazor/how-to/update-form-field-using-context-menu.md
Re-structing the How to section for the Blazor Pdfviewer
Nil.
> 983689: Modified the content the How to section for the blazor pdfviewer

- Document-Processing-toc.html
Hi All,
Task Id: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/984031
Task Name: Need to resolve TOC failures in UG documentation
Regards,
Sameerkhan N
> 984031-ug: Resolved TOC Failures.

- Document-Processing/PDF/Conversions/HTML-To-PDF/NET/blazor.md
- Document-Processing/PDF/PDF-Library/NET/tabcontent-support/Create-PDF-document-in-MaUI-JetBrains.md
Hi All,
Task Id: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/983650/
Task Name: Need to update Repo Revamp & UG-Related Blazor Corrections
Regards,
Sameerkhan N
> 983650-ug1: Added Blazor UG corrections in PDF library.

- Document-Processing/PDF/PDF-Library/NET/tabcontent-support/Create-PDF-document-in-Blazor-MaUI-VS-Code.md
- Document-Processing/PDF/PDF-Library/NET/tabcontent-support/Create-PDF-document-in-Blazor-MaUI-Visual-studio.md
- Document-Processing/PDF/PDF-Library/NET/tabcontent-support/Create-PDF-document-in-Blazor-WASM-JetBrains.md
- Document-Processing/PDF/PDF-Library/NET/tabcontent-support/Create-PDF-document-in-Blazor-WASM-VS-Code.md
- Document-Processing/PDF/PDF-Library/NET/tabcontent-support/Create-PDF-document-in-Blazor-WASM-Visual-studio.md
Hi All,
Task Id: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/983650/
Task Name: Need to update Repo Revamp & UG-Related Blazor Corrections
Regards,
Sameerkhan N
> 983650-2: Added Blazor UG correction in PDF library

- Document-Processing-toc.html
- Document-Processing/Word/Word-Processor/angular/restrict-editing.md
description:
984889: Make Restrict editing page available in Angular
> 984889: Make Restrict editing page available in Angular
